"""Explainable taxonomy of technology and workplace skills."""

from __future__ import annotations

SKILL_RULES: tuple[tuple[str, str, tuple[str, ...]], ...] = (
    ("Python", "programming_language", (r"(?<![\w.])python(?![\w.])",)),
    ("Java", "programming_language", (r"(?<![\w.])java(?!script)(?![\w.])",)),
    ("JavaScript", "programming_language", (r"\bjavascript\b", r"\bjava\s*script\b")),
    ("TypeScript", "programming_language", (r"\btypescript\b", r"\btype\s*script\b")),
    ("C#", "programming_language", (r"(?<!\w)c\s*#(?!\w)", r"\bcsharp\b")),
    ("C++", "programming_language", (r"(?<!\w)c\s*\+\+(?!\w)",)),
    ("C", "programming_language", (r"(?<![\w+#])c(?![\w+#])",)),
    ("Go", "programming_language", (r"\bgolang\b", r"\bgo\s+programming\b")),
    ("Kotlin", "programming_language", (r"\bkotlin\b",)),
    ("Swift", "programming_language", (r"\bswift\b",)),
    ("PHP", "programming_language", (r"\bphp\b",)),
    ("Ruby", "programming_language", (r"\bruby\b",)),
    ("Scala", "programming_language", (r"\bscala\b",)),
    ("R", "programming_language", (r"\br\s+programming\b", r"\busing\s+r\b")),
    ("SQL", "programming_language", (r"\bsql\b", r"\bstructured\s+query\s+language\b")),
    ("Bash", "programming_language", (r"\bbash\b", r"\bshell\s+scripting\b")),

    ("Spring Boot", "framework", (r"\bspring\s+boot\b",)),
    ("Spring", "framework", (r"\bspring\s+framework\b",)),
    (".NET", "framework", (r"(?<!\w)\.net(?!\w)", r"\bdotnet\b")),
    ("ASP.NET", "framework", (r"\basp\.?net\b",)),
    ("Django", "framework", (r"\bdjango\b",)),
    ("Flask", "framework", (r"\bflask\b",)),
    ("FastAPI", "framework", (r"\bfastapi\b", r"\bfast\s+api\b")),
    ("Node.js", "framework", (r"\bnode\.?js\b", r"\bnodejs\b")),
    ("Express.js", "framework", (r"\bexpress\.?js\b",)),
    ("React", "framework", (r"\breact(?:\.?js)?\b",)),
    ("Angular", "framework", (r"\bangular\b",)),
    ("Vue.js", "framework", (r"\bvue(?:\.?js)?\b",)),
    ("Next.js", "framework", (r"\bnext\.?js\b",)),
    ("Laravel", "framework", (r"\blaravel\b",)),
    ("Ruby on Rails", "framework", (r"\bruby\s+on\s+rails\b", r"\brails\b")),

    ("Machine Learning", "data_ai", (r"\bmachine\s+learning\b", r"\bml\b")),
    ("Artificial Intelligence", "data_ai", (r"\bartificial\s+intelligence\b", r"\bai\b")),
    ("Generative AI", "data_ai", (r"\bgenerative\s+ai\b", r"\bgenai\b", r"\bgen\s+ai\b")),
    ("Large Language Models", "data_ai", (r"\blarge\s+language\s+models?\b", r"\bllms?\b")),
    ("Natural Language Processing", "data_ai", (r"\bnatural\s+language\s+processing\b", r"\bnlp\b")),
    ("Computer Vision", "data_ai", (r"\bcomputer\s+vision\b",)),
    ("Data Science", "data_ai", (r"\bdata\s+science\b",)),
    ("Data Engineering", "data_ai", (r"\bdata\s+engineering\b",)),
    ("ETL", "data_ai", (r"\betl\b", r"\bextract[, ]+transform[, ]+load\b")),
    ("Apache Spark", "data_ai", (r"\bapache\s+spark\b", r"\bpyspark\b")),
    ("Pandas", "data_ai", (r"\bpandas\b",)),
    ("NumPy", "data_ai", (r"\bnumpy\b",)),
    ("scikit-learn", "data_ai", (r"\bscikit[- ]learn\b", r"\bsklearn\b")),
    ("TensorFlow", "data_ai", (r"\btensorflow\b",)),
    ("PyTorch", "data_ai", (r"\bpytorch\b",)),
    ("Databricks", "data_ai", (r"\bdatabricks\b",)),
    ("Snowflake", "data_ai", (r"\bsnowflake\b",)),
    ("dbt", "data_ai", (r"(?<!\w)dbt(?!\w)",)),

    ("AWS", "cloud", (r"\baws\b", r"\bamazon\s+web\s+services\b")),
    ("Azure", "cloud", (r"\bazure\b", r"\bmicrosoft\s+azure\b")),
    ("Google Cloud", "cloud", (r"\bgoogle\s+cloud\b", r"\bgcp\b")),
    ("Cloud Computing", "cloud", (r"\bcloud\s+computing\b",)),

    ("PostgreSQL", "database", (r"\bpostgres(?:ql)?\b",)),
    ("MySQL", "database", (r"\bmysql\b",)),
    ("Microsoft SQL Server", "database", (r"\bsql\s+server\b", r"\bmssql\b")),
    ("Oracle Database", "database", (r"\boracle\s+(?:database|db)\b",)),
    ("MongoDB", "database", (r"\bmongodb\b",)),
    ("Redis", "database", (r"\bredis\b",)),
    ("DynamoDB", "database", (r"\bdynamodb\b",)),
    ("Elasticsearch", "database", (r"\belasticsearch\b",)),
    ("Cassandra", "database", (r"\bcassandra\b",)),
    ("BigQuery", "database", (r"\bbigquery\b", r"\bbig\s+query\b")),

    ("Git", "devops", (r"\bgit\b", r"\bgithub\b", r"\bgitlab\b")),
    ("Docker", "devops", (r"\bdocker\b", r"\bcontainerisation\b", r"\bcontainerization\b")),
    ("Kubernetes", "devops", (r"\bkubernetes\b", r"\bk8s\b")),
    ("Terraform", "devops", (r"\bterraform\b",)),
    ("Jenkins", "devops", (r"\bjenkins\b",)),
    ("GitHub Actions", "devops", (r"\bgithub\s+actions\b",)),
    ("CI/CD", "devops", (r"\bci\s*/\s*cd\b", r"\bcontinuous\s+integration\b")),
    ("Linux", "devops", (r"\blinux\b",)),
    ("Microservices", "architecture", (r"\bmicroservices?\b",)),
    ("REST APIs", "architecture", (r"\brest(?:ful)?\s+apis?\b", r"\brest\s+services?\b")),
    ("GraphQL", "architecture", (r"\bgraphql\b",)),
    ("Kafka", "architecture", (r"\bapache\s+kafka\b", r"\bkafka\b")),
    ("RabbitMQ", "architecture", (r"\brabbitmq\b",)),
    ("Event-driven Architecture", "architecture", (r"\bevent[- ]driven\b",)),

    ("Unit Testing", "testing", (r"\bunit\s+tests?\b", r"\bunit\s+testing\b")),
    ("Test Automation", "testing", (r"\btest\s+automation\b", r"\bautomated\s+testing\b")),
    ("Selenium", "testing", (r"\bselenium\b",)),
    ("Cypress", "testing", (r"\bcypress\b",)),
    ("Playwright", "testing", (r"\bplaywright\b",)),
    ("JUnit", "testing", (r"\bjunit\b",)),
    ("pytest", "testing", (r"\bpytest\b",)),
    ("TDD", "testing", (r"\btdd\b", r"\btest[- ]driven\s+development\b")),

    ("Power BI", "analytics_tool", (r"\bpower\s*bi\b",)),
    ("Tableau", "analytics_tool", (r"\btableau\b",)),
    ("Looker", "analytics_tool", (r"\blooker\b",)),
    ("Excel", "analytics_tool", (r"\bmicrosoft\s+excel\b", r"\bexcel\b")),
    ("SAS", "analytics_tool", (r"\bsas\b",)),
    ("SAP", "enterprise_platform", (r"\bsap\b",)),
    ("Salesforce", "enterprise_platform", (r"\bsalesforce\b",)),
    ("ServiceNow", "enterprise_platform", (r"\bservicenow\b",)),
)

SOFT_SKILL_RULES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Communication", (r"\bcommunication\s+skills?\b", r"\bcommunicat(?:e|ion)\b")),
    ("Collaboration", (r"\bcollaborat(?:e|ion|ive)\b", r"\bteamwork\b")),
    ("Problem Solving", (r"\bproblem[- ]solving\b", r"\bsolve\s+complex\s+problems?\b")),
    ("Analytical Thinking", (r"\banalytical\s+(?:skills?|thinking)\b",)),
    ("Attention to Detail", (r"\battention\s+to\s+detail\b",)),
    ("Adaptability", (r"\badaptab(?:le|ility)\b", r"\bfast[- ]paced\b")),
    ("Leadership", (r"\bleadership\s+skills?\b",)),
    ("Stakeholder Management", (r"\bstakeholder\s+management\b",)),
    ("Time Management", (r"\btime\s+management\b",)),
    ("Curiosity", (r"\bcurios(?:ity|ious)\b",)),
)

DEGREE_FIELD_RULES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Computer Science", (r"\bcomputer\s+science\b",)),
    ("Information Technology", (r"\binformation\s+technology\b", r"\bit\s+degree\b")),
    ("Software Engineering", (r"\bsoftware\s+engineering\b",)),
    ("Information Systems", (r"\binformation\s+systems?\b",)),
    ("Data Science", (r"\bdata\s+science\b",)),
    ("Statistics", (r"\bstatistics?\b", r"\bstatistical\s+science\b")),
    ("Mathematics", (r"\bmathematics?\b", r"\bmathematical\s+science\b")),
    ("Engineering", (r"\bengineering\s+degree\b", r"\bdegree\s+in\s+engineering\b")),
    ("Business", (r"\bbusiness\s+(?:degree|discipline|field)\b",)),
    ("Finance", (r"\bfinance\s+(?:degree|discipline|field)\b",)),
)

DEGREE_REQUIRED_PATTERNS: tuple[str, ...] = (
    r"\b(?:bachelor'?s?|bsc|b\.sc\.?|btech|b\.tech\.?|undergraduate)\s+(?:degree|qualification)\b",
    r"\bdegree\s+(?:in|required|essential)\b",
    r"\brelevant\s+(?:tertiary\s+)?qualification\b",
    r"\bcomputer\s+science\s+degree\b",
)

DEGREE_OPTIONAL_PATTERNS: tuple[str, ...] = (
    r"\bdegree\s+(?:is\s+)?(?:preferred|advantageous|a\s+plus)\b",
    r"\bor\s+equivalent\s+(?:experience|practical\s+experience)\b",
)
